# Этот стартовый рабочий процесс предназначен для проекта CMake, работающего на одной платформе.
# Существует другой стартовый рабочий процесс, если вам необходимо кроссплатформенное покрытие.
# См.: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

name: CMake на одной платформе

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Настройте тип сборки CMake здесь (Release, Debug, RelWithDebInfo и т.д.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


    - name: Создание артефакта
      run: |
        mkdir ${{github.workspace}}/build/Release/scf.dll
        echo ${{github.workspace}}/build/Release/scf.dll

    - name: Загрузка артефакта
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: output/artifact.dll


